language: node_js
dist: trusty
sudo: required

notifications:
  email:
    on_success: always
    on_failure: always

services:
  - docker

before_install:
  - docker pull jpcercal/cercal.io:latest

install:
  - docker run -v $PWD:/usr/share/blog jpcercal/cercal.io:latest /bin/bash -l -c "npm install"
  - docker run -v $PWD:/usr/share/blog jpcercal/cercal.io:latest /bin/bash -l -c "npm run napa"

script:
  - docker run -v $PWD:/usr/share/blog jpcercal/cercal.io:latest /bin/bash -l -c "BASE_URL=$BASE_URL grunt production"

after_success:
  - docker login -u jpcercal -p $DOCKER_PASSWORD
  - docker tag jpcercal/cercal.io:latest jpcercal/cercal.io:$TRAVIS_BUILD_NUMBER
  - docker push jpcercal/cercal.io

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: gh-pages
  on:
    branch: master

after_deploy:
  - docker run -v $PWD:/usr/share/blog jpcercal/cercal.io:latest /bin/bash -l -c "GOOGLE_API_KEY=$GOOGLE_API_KEY grunt pagespeed"
