language: node_js

sudo: required

services:
  - docker

before_install:
  - docker build -t cercal.io .

install:
  - docker run -v $PWD:/usr/share/blog cercal.io /bin/bash -l -c "npm install"
  - docker run -v $PWD:/usr/share/blog cercal.io /bin/bash -l -c "npm run napa"

before_script:
  - git clone -b master https://github.com/jpcercal/cercal.io.git public/

script:
  - docker run -v $PWD:/usr/share/blog cercal.io /bin/bash -l -c "BASE_URL=$BASE_URL grunt production"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    all_branches: true
