archetypeDir: "archetypes"
contentDir:   "content"
layoutDir:    "layouts"
publishDir:   "public"
dataDir:      "data"
staticDir:    "static"
themesDir:    "themes"
theme:        ""
baseURL:      "https://cercal.io/"

taxonomies:
  tag: "tags"
  category: "categories"
  author: "authors"

disqusShortname:  "Cercal.IO"
defaultLayout:    "post"
defaultExtension: "html"
metaDataFormat:   "yaml"
googleAnalytics:  ""

pygmentsUseClasses:             true
pygmentsCodeFences:             true
pygmentsOptions:                "linenos=true,linespans=line"
languageCode:                   "pt"
defaultContentLanguage:         "pt"
defaultContentLanguageInSubdir: false
enableMissingTranslationPlaceholders: false

languages:
  en:
    title: "Cercal.IO"
    locale: "en"
    description: "English"
  pt:
    title: "Cercal.IO"
    locale: "pt"
    description: "Português"

rssLimit:     15
paginate:     10
paginatePath: "page"
permalinks:
  post: /:slug/

stepAnalysis: true
noChmod:      false
noTimes:      false
buildDrafts:  false
buildFuture:  false
buildExpired: false
relativeURLs: false
canonifyURLs: false

logFile:      "hugo.log"
log:          true
verbose:      false
verboseLog:   true

disablePathToLower:         false
watch:                      true
disableLiveReload:          false
enableGitInfo:              false
enableRobotsTXT:            true
disableHugoGeneratorInject: true
enableEmoji:                false

footnoteAnchorPrefix:       ""
footnoteReturnLinkContents: ""

disableKinds: 
  - "section"

ignoreFiles: 
  - "Thumbs\\.db$"
  - "\\.DS_Store$"
  - "\\.log$"
  - "\\.lock$"
  - "\\.sw?$"
